param_names = ["Autosized Coil Airflow?",
"Autosized Coil Capacity?",
"Autosized Coil Water Flow?",
"Coil Air Mass Flow Rate at Ideal Loads Peak",
"Coil Air Mass Flow Rate at Rating Conditions",
"Coil Air Volume Flow Rate at Ideal Loads Peak",
"Coil Capacity Percentage of Plant Design Capacity",
"Coil Entering Air Drybulb at Ideal Loads Peak",
"Coil Entering Air Drybulb at Rating Conditions",
"Coil Entering Air Enthalpy at Ideal Loads Peak",
"Coil Entering Air Enthalpy at Rating Conditions",
"Coil Entering Air Humidity Ratio at Ideal Loads Peak",
"Coil Entering Air Humidity Ratio at Rating Conditions",
"Coil Entering Air Wetbulb at Ideal Loads Peak",
"Coil Entering Air Wetbulb at Rating Conditions",
"Coil Entering Plant Fluid Temperature at Ideal Loads Peak",
"Coil Final Gross Sensible Capacity",
"Coil Final Gross Total Capacity",
"Coil Final Reference Air Volume Flow Rate",
"Coil Final Reference Plant Fluid Volume Flow Rate",
"Coil Fluid Flow Rate Percentage of Plant Design Flow Rate",
"Coil Leaving Air Drybulb at Ideal Loads Peak",
"Coil Leaving Air Drybulb at Rating Conditions",
"Coil Leaving Air Enthalpy at Ideal Loads Peak",
"Coil Leaving Air Enthalpy at Rating Conditions",
"Coil Leaving Air Humidity Ratio at Ideal Loads Peak",
"Coil Leaving Air Humidity Ratio at Rating Conditions",
"Coil Leaving Air Wetbulb at Ideal Loads Peak",
"Coil Leaving Air Wetbulb at Rating Conditions",
"Coil Leaving Plant Fluid Temperature at Ideal Loads Peak",
"Coil Location",
"Coil Off-Rating Capacity Modifier at Ideal Loads Peak",
"Coil Plant Fluid Mass Flow Rate at Ideal Loads Peak",
"Coil Plant Fluid Temperature Difference at Ideal Loads Peak",
"Coil Sensible Capacity at Ideal Loads Peak",
"Coil Sensible Capacity at Rating Conditions",
"Coil Total Capacity at Ideal Loads Peak",
"Coil Total Capacity at Rating Conditions",
"Coil Type",
"Coil U-value Times Area Value",
"Coil and Fan Net Total Capacity at Ideal Loads Peak",
"DX Coil Capacity Decrease Ratio from Too High Flow/Capacity Ratio",
"DX Coil Capacity Increase Ratio from Too Low Flow/Capacity Ratio",
"Date/Time at Air Flow Ideal Loads Peak",
"Date/Time at Sensible Ideal Loads Peak",
"Date/Time at Total Ideal Loads Peak",
"Design Day Name at Air Flow Ideal Loads Peak",
"Design Day Name at Sensible Ideal Loads Peak",
"Design Day Name at Total Ideal Loads Peak",
"Dry Air Heat Capacity",
"HVAC Name",
"HVAC Type",
"Moist Air Heat Capacity",
"OA Pretreated prior to coil inlet?",
"Outdoor Air Drybulb at Ideal Loads Peak",
"Outdoor Air Flow Percentage at Ideal Loads Peak",
"Outdoor Air Humidity Ratio at Ideal Loads Peak",
"Outdoor Air Volume Flow Rate at Ideal Loads Peak",
"Outdoor Air Wetbulb at Ideal Loads Peak",
"Plant Design Capacity",
"Plant Design Fluid Return Temperature",
"Plant Design Fluid Supply Temperature",
"Plant Design Fluid Temperature Difference",
"Plant Fluid Density",
"Plant Fluid Specific Heat Capacity",
"Plant Maximum Fluid Mass Flow Rate",
"Plant Name for Coil",
"Standard Air Density Adjusted for Elevation",
"Supply Fan Air Heat Gain at Ideal Loads Peak",
"Supply Fan Maximum Air Mass Flow Rate",
"Supply Fan Maximum Air Volume Flow Rate",
"Supply Fan Name for Coil",
"Supply Fan Type for Coil",
"System Return Air Drybulb at Ideal Loads Peak",
"System Return Air Humidity Ratio at Ideal Loads Peak",
"System Sizing Method Air Flow",
"System Sizing Method Capacity",
"System Sizing Method Concurrence",
"Terminal Unit Reheat Coil Multiplier",
"Zone Air Drybulb at Ideal Loads Peak",
"Zone Air Humidity Ratio at Ideal Loads Peak",
"Zone Air Relative Humidity at Ideal Loads Peak",
"Zone Latent Heat Gain at Ideal Loads Peak",
"Zone Name(s)",
"Zone Sensible Heat Gain at Ideal Loads Peak"]

param_names.each_with_index do |val, key|
  symbol = val.gsub(/[-\s+\/]/, "_").gsub(/[()\?]/, "").downcase.to_sym
  puts ":#{symbol}, "
  #puts "{:index => #{key}, :name => :#{symbol}, :type => 'double'},"
end